Added check-files job to ensure that required workflows runs when there are changes right files (#3030)
* Added check-files job to ensure that required workflows runs when there are changes right files

Signed-off-by: Navneet Verma <navneev@amazon.com>

* using a composite function

Signed-off-by: Navneet Verma <navneev@amazon.com>

---------

Signed-off-by: Navneet Verma <navneev@amazon.com>

diff --git a/.github/workflows/remote_index_build.yml b/.github/workflows/remote_index_build.yml
--- a/.github/workflows/remote_index_build.yml
+++ b/.github/workflows/remote_index_build.yml
@@ -6,31 +6,28 @@ on:
     branches:
       - "*"
       - "feature/**"
-    paths:
-      - 'build.gradle'
-      - 'settings.gradle'
-      - 'src/**'
-      - 'build-tools/**'
-      - 'buildSrc/**'
-      - 'gradle/**'
-      - 'jni/**'
-      - '.github/workflows/remote_index_build.yml'
   pull_request:
     branches:
       - "*"
       - "feature/**"
-    paths:
-      - 'build.gradle'
-      - 'settings.gradle'
-      - 'src/**'
-      - 'build-tools/**'
-      - 'buildSrc/**'
-      - 'gradle/**'
-      - 'jni/**'
-      - '.github/workflows/remote_index_build.yml'
 
 jobs:
+  check-files:
+    name: Check file for Build and Test k-NN using Remote Index Builder
+    runs-on: ubuntu-latest
+    outputs:
+      RUN_IT_TEST: ${{ steps.check.outputs.files_changed }}
+    steps:
+      - uses: actions/checkout@v6
+      - name: Check files
+        id: check
+        uses: ./.github/actions/check-files
+        with:
+          files: .github/workflows/remote_index_build.yml
+
   Remote-Index-Build-IT-Tests:
+    needs: check-files
+    if: needs.check-files.outputs.RUN_IT_TEST == 'true'
     strategy:
       matrix:
         java: [21]
@@ -151,3 +148,14 @@ jobs:
           docker logout
           rm -rf ${{ github.workspace }}/*
 
+  check-results:
+    needs: [check-files, Remote-Index-Build-IT-Tests]
+    if: always()
+    name: Check results for Build and Test k-NN using Remote Index Builder
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check results
+        if: ${{ needs.check-files.outputs.RUN_IT_TEST && needs.Remote-Index-Build-IT-Tests.result == 'failure' }}
+        run: |
+          echo "Remote Integration tests failed, failing the check-results step"
+          exit 1
